'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {metric, clock, imageUrl, localDay, targetSummary} = require('../static/daily-feedback.js');
assert.equal(metric({expected:true, verified:false, current:0}, 'talisman'), '未核验');
assert.equal(metric({expected:true, verified:false, current:30, total:30}, 'collective'), '未核验');
assert.equal(metric({expected:true, verified:true, current:0}, 'talisman'), '0');
assert.equal(metric({expected:true, verified:true, current:113, target:100, total:null}, 'talisman'), '113');
assert.equal(targetSummary({verified:true, current:113, target:100}), '目标 100 · 已达标');
assert.equal(targetSummary({verified:true, current:80, target:100}), '目标 100 · 未达标');
assert.equal(targetSummary({verified:true, current:113, target:null}), '经验已读取 · 目标未核验');
assert.equal(targetSummary({verified:false, current:100, target:100}), '');
assert.equal(metric({expected:true, verified:true, current:25, total:30}, 'collective'), '25/30');
assert.equal(metric({expected:false, verified:false}, 'collective'), '今日无需验收');
assert.equal(clock(null), '尚未采集');
assert.equal(clock('2026-10-07T21:10:00+08:00'), '21:10 采集');
assert.equal(imageUrl('05-测试', '2026-10-07', 'talisman-a.png'), '/api/daily-feedback/05-%E6%B5%8B%E8%AF%95/images/talisman-a.png?date=2026-10-07');
assert.match(localDay(), /^\d{4}-\d{2}-\d{2}$/);
const source = fs.readFileSync(path.join(__dirname, '../static/daily-feedback.js'), 'utf8');
assert(!source.includes('innerHTML'), 'Evidence/account labels must render through textContent');
assert(!source.includes("method: 'POST'"), 'Verification page must not start, stop, or change tasks');
assert(source.includes("document.hidden"), 'Polling pauses while phone page is hidden');
assert(source.includes('推送服务已接收'), 'Accepted delivery must not claim iPhone receipt');
console.log('Daily feedback display helpers and read-only rendering: passed');
